/**
 * Don't try this at home kids.
 */
#include <stdio.h>

void gotoMadness() {
	goto start;
	start: goto bzv;
	esk: putchar('g'); goto pnf;
	nok: goto fqc;
	wxc: goto hxm;
	nue: goto yzn;
	vuy: goto ynu;
	mlj: goto zhw;
	iac: goto mlv;
	oxv: goto vus;
	mde: goto inj;
	hmi: goto bmd;
	cwd: goto dry;
	bex: goto afo;
	dhv: goto qzi;
	zlo: goto act;
	vub: goto pwm;
	bhe: putchar('.'); goto ztl;
	cpk: goto uxn;
	dqa: goto mxf;
	xel: putchar(' '); goto rsg;
	gxd: goto ikw;
	wht: goto rjm;
	tlj: goto jfx;
	jeg: goto xsl;
	xcd: putchar('l'); goto qjy;
	xwk: goto hco;
	dbq: goto fkr;
	wez: goto nok;
	xyr: putchar('b'); goto fmu;
	cga: goto aps;
	qwh: goto ihs;
	myc: goto ahv;
	fei: goto elt;
	mdt: putchar('i'); goto mqg;
	rsg: goto ucn;
	vtg: goto xto;
	ade: goto ahs;
	ory: goto rnf;
	lok: goto mic;
	pkr: goto abp;
	nsr: putchar('r'); goto xol;
	dqb: putchar('n'); goto ofb;
	poz: goto lic;
	cug: goto iuw;
	eom: goto zfy;
	awj: goto cax;
	xol: goto bsl;
	cad: goto wez;
	rjm: goto lwa;
	hco: goto xsp;
	tnj: goto ihc;
	vfs: goto xcd;
	esz: goto cga;
	sym: goto fiq;
	cnz: goto tue;
	rqs: goto cyq;
	eqf: goto sed;
	blm: goto heb;
	ins: goto vuy;
	rsu: goto rlj;
	tgf: goto gps;
	rav: goto uwm;
	yvl: goto gpx;
	fag: goto lgm;
	siz: goto afq;
	qlg: goto dsi;
	jfx: goto ygl;
	jum: goto jev;
	ahs: goto yis;
	nfb: putchar('y'); goto cvl;
	gah: goto skb;
	bye: goto xly;
	zvl: goto msa;
	zxu: goto tzo;
	efk: goto mft;
	bvd: goto esk;
	tdx: putchar('e'); goto mbw;
	cpu: goto lgv;
	zum: goto woh;
	wsn: goto uzf;
	gzv: goto icx;
	ilu: goto ajc;
	piw: goto lke;
	oed: putchar('r'); goto qnm;
	fds: goto ory;
	yiz: goto ihl;
	tvq: goto sal;
	uaz: goto wsn;
	dnb: goto poh;
	rxd: goto kbl;
	xra: putchar('m'); goto mwc;
	onb: goto nfb;
	zug: putchar('t'); goto iom;
	pxa: goto uez;
	znl: goto cxv;
	qgd: goto ypz;
	jfl: goto pgv;
	wsx: goto hal;
	whr: goto lmr;
	zmx: goto ycu;
	vlx: putchar(' '); goto lcs;
	qzy: goto xbg;
	mol: goto gis;
	dsj: goto kor;
	fhw: goto mfa;
	pwl: putchar('!'); goto oqt;
	klg: goto jku;
	owp: goto trw;
	gps: goto gup;
	hgs: goto ben;
	tue: goto iac;
	akc: putchar('f'); goto fdo;
	qfl: goto ngf;
	bpm: putchar(' '); goto dcz;
	aps: goto juh;
	mlv: goto szi;
	qwp: goto kbi;
	nzg: putchar('e'); goto vma;
	abp: goto pah;
	sup: goto cof;
	fny: goto dvx;
	cky: goto puj;
	qpd: goto cox;
	dah: goto gre;
	vsn: goto knx;
	aod: goto ibr;
	lzc: goto zlr;
	vuo: goto hgz;
	jue: goto pau;
	cvl: goto xuj;
	rgs: goto gke;
	kpa: goto vfs;
	boq: goto xft;
	oag: goto beq;
	ikg: goto tib;
	ayi: goto ymf;
	lwa: putchar('i'); goto osz;
	afo: goto jue;
	msu: goto vkd;
	smy: goto tnj;
	hca: putchar(' '); goto iak;
	ajm: goto yfc;
	gis: goto szp;
	jop: goto iks;
	ahv: putchar('u'); goto bye;
	skf: goto wxp;
	etg: putchar(' '); goto dhv;
	mhp: goto ozj;
	ymf: goto nsr;
	dri: goto slb;
	qhs: putchar('T'); goto aht;
	jbt: goto xel;
	zhw: goto bhe;
	jdp: goto vut;
	urv: goto vcj;
	deb: putchar('n'); goto jnf;
	wft: goto zhi;
	cuh: goto ljd;
	ben: goto qxv;
	wsm: goto sxw;
	sap: putchar('T'); goto ocj;
	que: goto zxm;
	alm: goto kja;
	jcl: goto tqk;
	uod: goto sey;
	lnj: goto dgs;
	uaq: goto qbf;
	nrp: goto pxa;
	jgz: goto gbh;
	sal: goto rou;
	ndb: goto zkf;
	hzm: goto kwj;
	tqc: goto nxt;
	yqb: goto nzg;
	mfa: goto zxu;
	api: putchar('g'); goto hmi;
	ajv: goto qpz;
	sli: goto pkr;
	mbw: goto mtz;
	dia: goto fei;
	kyo: goto ngc;
	hjc: goto vne;
	woh: putchar('S'); goto gih;
	icx: goto bzi;
	iom: goto tqu;
	tir: goto qwe;
	knx: goto qrk;
	vgw: goto vuo;
	ijs: goto ndb;
	bjq: goto mvg;
	ztp: goto kba;
	tkb: goto fkg;
	shj: goto hyr;
	wbm: goto mxc;
	ucf: goto hel;
	rou: goto cnz;
	lgv: goto kcx;
	wuz: goto lmg;
	dry: goto xdu;
	fjg: putchar('r'); goto fyi;
	vkd: goto asd;
	gih: goto hca;
	asd: putchar('u'); goto qtg;
	rzf: goto kms;
	dgs: goto wga;
	uxn: goto fjg;
	qbf: goto odh;
	ljd: goto rho;
	vgy: putchar('i'); goto trq;
	wbt: goto lhd;
	fqc: goto zos;
	ide: goto wnm;
	shl: goto fny;
	mvg: goto tfp;
	bda: goto rtc;
	hkl: goto nej;
	ojn: goto rkx;
	wnm: goto qfl;
	kob: goto aqs;
	inj: goto fgz;
	fbh: goto cvq;
	iaz: goto skr;
	zvh: goto lty;
	fqz: goto pir;
	gfh: goto uie;
	uie: goto box;
	jxi: goto ufk;
	hcs: goto dtr;
	hfz: goto skg;
	rpe: putchar('n'); goto pxr;
	fqb: goto oed;
	ftq: goto osl;
	mgd: goto tqo;
	caf: goto vzd;
	byz: goto uaq;
	juv: goto dxa;
	nxt: putchar('a'); goto jan;
	yme: goto qgd;
	rho: putchar('d'); goto uaf;
	iou: goto fqg;
	juh: putchar('m'); goto wsm;
	ukd: goto jbm;
	dvx: goto tcp;
	bzi: goto bzx;
	alq: goto fjn;
	qkw: goto zvh;
	ihv: goto fxp;
	fvc: goto gli;
	gdf: goto jdp;
	iak: goto bld;
	kms: putchar(' '); goto wfl;
	wbu: goto mwz;
	plc: goto rfg;
	bpl: goto boy;
	pmb: goto ilu;
	leq: goto wbm;
	rha: goto uiz;
	hxf: goto crv;
	bnh: goto ltq;
	okm: putchar('e'); goto gec;
	mic: goto wuz;
	poh: goto zum;
	raw: goto bdu;
	fqg: goto rcn;
	qzv: putchar('I'); goto pgl;
	ypv: goto ghs;
	gqz: putchar('o'); goto mhp;
	tlq: goto kvm;
	wuo: goto gqz;
	gli: goto sup;
	tqk: goto ihv;
	qwe: putchar('t'); goto ijs;
	fyi: goto oyj;
	fic: putchar('y'); goto jxn;
	lic: putchar('p'); goto ihr;
	chv: goto opt;
	lhd: goto wfc;
	oqt: goto hcs;
	ugm: goto dqb;
	xon: goto cpu;
	gre: goto ejg;
	ubi: putchar('.'); goto vol;
	ihs: putchar(' '); goto ury;
	ocj: goto dia;
	opf: goto oue;
	sxw: goto xbm;
	kba: goto xjq;
	uez: putchar('h'); goto wxh;
	iks: goto gfc;
	isp: putchar(' '); goto xdo;
	hys: goto jlx;
	ngy: goto kuo;
	odi: goto jop;
	ert: putchar('u'); goto dah;
	xdo: goto elq;
	gtj: goto euc;
	hgz: goto jwo;
	qot: goto wmu;
	bjr: goto qpr;
	hyr: goto ngy;
	done: return;
	bkm: goto msu;
	elq: goto sud;
	ajc: goto ugm;
	lty: goto ojn;
	ihr: goto cpk;
	pau: goto vnk;
	juy: goto nkb;
	mwv: goto hfz;
	uow: putchar('o'); goto ioj;
	geo: goto ump;
	ibr: putchar('t'); goto odi;
	tmi: goto qod;
	rtv: putchar('t'); goto zrm;
	epu: goto wxc;
	xuy: putchar('d'); goto kau;
	uaf: goto pdx;
	iug: goto wta;
	taw: goto ahp;
	pec: goto jbt;
	qor: goto bgt;
	fmu: goto shj;
	tdo: goto byz;
	msa: goto yah;
	qxv: goto ajv;
	lcp: goto wlr;
	wsu: goto ebu;
	uam: goto dbq;
	kcx: goto fxn;
	lqz: goto fgj;
	rut: goto bna;
	tfp: putchar('g'); goto kty;
	yis: putchar(' '); goto oaq;
	imk: goto diu;
	ghs: goto gqy;
	izh: putchar('S'); goto qot;
	plr: putchar(' '); goto tkb;
	ndm: goto svt;
	drh: goto hkl;
	ctf: goto umf;
	gti: putchar('B'); goto ins;
	zhg: goto vrh;
	lia: goto hxo;
	rnf: goto boq;
	tuz: goto mov;
	qzi: goto sym;
	dms: goto fvc;
	jxn: goto scj;
	nzw: goto ulm;
	pah: goto rzf;
	ofb: goto bvd;
	lce: goto okm;
	fdo: goto que;
	jbk: goto ftq;
	acb: goto uow;
	pbj: goto iou;
	lmg: goto imk;
	ztl: goto wyj;
	gnb: goto csi;
	mxb: goto tlq;
	tor: goto auj;
	mwc: goto uaz;
	umv: goto riv;
	cvq: putchar(' '); goto bpr;
	ndx: goto xra;
	wlr: goto pms;
	aed: goto hml;
	qpz: goto aig;
	bjx: goto gdf;
	wfc: goto acg;
	cxv: goto shi;
	osz: goto bex;
	cox: goto qlg;
	zxm: goto bkm;
	ahp: goto rxd;
	rkx: goto cxy;
	xly: goto kob;
	qjy: goto psf;
	heb: goto biu;
	jwo: goto ugf;
	aqs: goto qwp;
	mft: goto tqc;
	ucj: goto duj;
	cgv: goto mde;
	dyo: goto qor;
	bsl: putchar('e'); goto tmi;
	cof: goto fre;
	uzf: putchar('i'); goto bjx;
	hal: putchar('h'); goto fqz;
	fgj: putchar('e'); goto piw;
	uta: goto vyt;
	box: goto wft;
	teu: goto dwh;
	dsi: putchar('a'); goto oei;
	zsc: goto smy;
	sau: goto plc;
	skb: goto upc;
	sey: goto utx;
	bgt: goto sau;
	rlh: goto akc;
	kum: putchar('c'); goto atr;
	mwz: goto mlj;
	dcz: goto gah;
	yfc: goto ert;
	rmd: putchar('S'); goto whr;
	ygl: goto icu;
	qpr: goto ezu;
	ezu: goto uoc;
	ihc: goto siz;
	kbi: goto deb;
	rvo: goto lih;
	ocw: goto xuy;
	pir: goto uzn;
	kja: goto ctf;
	rlj: goto ltm;
	biu: putchar('.'); goto mky;
	ury: goto ucf;
	kwd: goto aed;
	ngc: goto awj;
	trw: goto jpx;
	ebu: goto ayi;
	xdu: goto chv;
	xvr: goto fbh;
	xjq: goto vgw;
	xft: putchar('A'); goto sno;
	bpr: goto zjk;
	atn: goto rbg;
	aht: goto tsp;
	boy: goto bpm;
	fjn: goto cmk;
	shi: goto nad;
	uiz: putchar(' '); goto izu;
	yzn: goto yxp;
	lcs: goto tyd;
	qod: goto zhg;
	hxm: goto fli;
	xvp: goto mvw;
	vhe: goto kum;
	pgv: goto kpa;
	oue: putchar('a'); goto qzy;
	opt: goto vfc;
	mxc: goto qbs;
	xki: goto ism;
	xsl: putchar('a'); goto wsu;
	crv: goto xuq;
	kvf: putchar('h'); goto qkw;
	iaw: goto thj;
	cyq: goto etg;
	zpu: goto klg;
	zos: goto txg;
	lgm: goto jcl;
	ycu: goto cuv;
	acg: putchar('o'); goto dsj;
	cmk: goto hlc;
	hml: goto itk;
	wfl: goto iug;
	mfe: goto izh;
	ltq: putchar('e'); goto qwh;
	lih: goto juv;
	itk: goto lce;
	fxn: goto ocw;
	lgo: goto gvn;
	wyj: goto bpl;
	fmh: goto xwk;
	wxh: goto hgy;
	rwf: goto taw;
	qtg: goto enw;
	fib: putchar('s'); goto cky;
	omx: goto nmw;
	vcj: goto jfm;
	tzo: goto wsx;
	xbg: goto jdv;
	trq: goto pmb;
	rzq: putchar('g'); goto ikx;
	zus: goto bnu;
	mqg: goto zvl;
	vyt: goto ysf;
	fkr: goto qct;
	ilh: goto vhe;
	jpx: goto drh;
	jnf: goto shl;
	agk: putchar('l'); goto ckh;
	kau: goto boh;
	itp: goto yjg;
	vus: goto jeg;
	tsp: goto bjr;
	lpr: goto lgo;
	xvb: goto isp;
	rel: goto seu;
	qlb: goto myr;
	tqu: goto sli;
	gup: putchar('u'); goto stq;
	zfn: goto dmn;
	ulm: goto yqb;
	nht: goto ask;
	mov: goto qcs;
	lrm: putchar('f'); goto qvg;
	dmn: putchar('P'); goto fds;
	rdh: goto wht;
	ozj: goto fag;
	uoc: putchar('A'); goto tpe;
	wvt: goto cfl;
	ckh: goto wal;
	ukp: goto noq;
	jdv: putchar(' '); goto xjd;
	rtc: goto uxd;
	hlc: goto bda;
	slb: goto aco;
	mle: goto rtv;
	zvp: goto jfl;
	few: goto oag;
	nej: goto sma;
	ikx: goto xki;
	bgm: goto qlb;
	ufk: goto gzv;
	act: goto ekm;
	ikw: goto ide;
	tqo: putchar('R'); goto jgz;
	tcs: goto tdx;
	ngj: goto tir;
	jku: goto ays;
	vfc: putchar('U'); goto npr;
	pdx: goto sqh;
	qrk: goto alq;
	oyj: goto yjk;
	krg: goto ukd;
	gbh: goto fcw;
	vut: goto gxd;
	qct: putchar('a'); goto tvq;
	odh: goto rav;
	aig: goto rlh;
	ekm: goto lrm;
	qnt: goto xev;
	ump: goto eom;
	beq: putchar('o'); goto dri;
	zrm: goto hzm;
	fkg: goto tor;
	stq: goto uqe;
	eyx: goto zvp;
	upc: goto vtg;
	duj: putchar('u'); goto teu;
	nad: goto fib;
	afq: putchar('e'); goto gfh;
	riv: goto sap;
	gec: goto dyo;
	ytc: goto iaw;
	nic: goto ukp;
	chq: goto ade;
	bdu: goto ftd;
	cuv: goto qzv;
	wmu: goto tun;
	sed: goto kbh;
	bna: goto dnb;
	fre: goto oxv;
	boh: goto qpd;
	vzd: goto zug;
	ynu: goto zor;
	pxr: goto lfe;
	mvw: goto eqf;
	elt: goto lia;
	umf: goto lqz;
	jbm: goto wuo;
	nxp: goto bgm;
	auj: goto poz;
	kuo: goto mdt;
	gfc: putchar('t'); goto onb;
	yah: goto uta;
	utx: putchar('t'); goto zpu;
	lfe: goto pwl;
	psf: goto dqa;
	jev: goto rkc;
	yxp: goto mle;
	ays: goto hjc;
	tpe: goto ubi;
	hgm: goto omx;
	cfl: putchar(' '); goto lpr;
	izu: goto jxi;
	lmr: goto mir;
	ioj: goto tgf;
	puj: goto vgy;
	cgy: goto yov;
	zfy: goto iyv;
	bld: goto rvo;
	xuj: putchar(' '); goto hgs;
	bzv: goto geo;
	qcs: goto skf;
	dps: goto esz;
	ihl: goto rgs;
	lmf: goto rut;
	ouy: goto bnf;
	kor: goto vub;
	vca: goto rel;
	fgz: goto api;
	jfm: goto wvt;
	jlx: goto tjl;
	gdn: goto dgj;
	skr: goto qnt;
	qnm: goto ndm;
	enw: goto ztp;
	wta: goto quo;
	zor: goto tcs;
	osl: goto kvf;
	yjg: goto bjq;
	nmw: goto bnh;
	fxp: goto ngj;
	noq: goto snh;
	abl: putchar('r'); goto btz;
	vol: goto mxb;
	ixe: putchar(';'); goto yvl;
	bnf: goto fic;
	fli: goto ndx;
	txg: goto lcp;
	npr: goto znl;
	vwr: goto rdh;
	zlr: goto uwf;
	srn: goto gnb;
	pgl: goto pbj;
	pnf: goto chq;
	usb: goto aod;
	oei: goto vca;
	krl: goto iaz;
	mio: goto alm;
	skg: putchar('I'); goto cad;
	sma: putchar('\n'); goto vsn;
	yut: goto rmd;
	xuq: putchar(' '); goto vwr;
	ysf: goto caf;
	atr: goto dms;
	tjl: goto nue;
	lke: goto efk;
	mtz: goto rha;
	bcz: goto nrp;
	uwm: goto abl;
	uxd: putchar('\n'); goto cwd;
	ucn: goto juy;
	cxy: goto xvp;
	zjk: goto yju;
	pwm: goto cuh;
	svt: goto mio;
	rcn: putchar('t'); goto kyo;
	gvn: goto epu;
	quo: goto myc;
	cax: goto urv;
	hel: goto nxp;
	ism: goto cgy;
	sqh: goto hgm;
	tpv: goto ilh;
	qvg: goto ucj;
	wga: goto gtj;
	xsp: goto syq;
	ltm: goto xaq;
	kst: goto atn;
	eht: goto nzw;
	tun: goto zfn;
	jeq: goto uam;
	tyd: goto mfe;
	bnu: goto cgv;
	qbs: goto lmf;
	yov: goto fhw;
	hxo: goto nic;
	euc: goto xyr;
	bzx: goto tpv;
	btz: goto fml;
	xaq: goto foy;
	dxa: goto mwv;
	scj: goto yme;
	gwi: goto jum;
	kwj: goto pec;
	vrh: goto zlo;
	csi: goto rqs;
	wal: goto krl;
	szp: goto eyx;
	ask: goto eht;
	ypz: goto acb;
	wxp: goto gti;
	fml: goto gdn;
	rbg: goto wbt;
	bmd: goto krg;
	gpx: goto ytc;
	ejg: goto itp;
	kbl: goto qhs;
	vne: goto jbk;
	fcw: goto rwf;
	diu: goto ouy;
	gqy: putchar('s'); goto cug;
	kbh: putchar('o'); goto rsu;
	iuw: goto plr;
	syq: goto hxf;
	vnk: goto ypv;
	aco: goto fmh;
	tcp: goto fqb;
	xbm: goto jeq;
	mxf: goto kwd;
	ugf: goto rpe;
	icu: goto wbu;
	mir: goto raw;
	xto: goto zmx;
	oaq: goto zus;
	sno: goto mgd;
	uqe: goto tdo;
	kvm: goto owp;
	thj: putchar(')'); goto done;
	uzn: goto hys;
	ngf: goto rzq;
	vma: goto usb;
	uwf: goto awy;
	jan: goto xon;
	rkc: putchar('I'); goto leq;
	szi: putchar('k'); goto zsc;
	iyv: goto umv;
	awy: goto ixe;
	dtr: goto xvr;
	foy: goto ajm;
	mky: goto xvb;
	pms: goto yut;
	yju: goto tuz;
	seu: putchar('b'); goto mol;
	nkb: goto dps;
	tib: goto lnj;
	yjk: goto nht;
	hgy: goto tlj;
	dwh: goto agk;
	fiq: putchar('c'); goto kst;
	sud: goto lzc;
	lje: goto gwi;
	myr: goto opf;
	xjd: goto ikg;
	rfg: goto blm;
	gke: goto few;
	ftd: goto vlx;
	dgj: goto srn;
	zhi: putchar(' '); goto lok;
	kty: goto bcz;
	xev: putchar(' '); goto uod;
	zkf: goto yiz;
	snh: putchar('H'); goto lje;
}

int main() {
	gotoMadness();

	return 0;
}
