/**
 * Don't try this at home kids.
 */
#include <stdio.h>

void gotoMadness() {
	goto start;
	start: goto pzr;
	zdx: goto idb;
	lhg: goto yln;
	kxw: goto giz;
	jhp: goto fks;
	yum: goto ouj;
	ybm: goto tna;
	axm: putchar(' '); goto eun;
	jzi: goto hft;
	xeq: goto kdt;
	sqh: goto zqm;
	vxa: goto zfs;
	ves: goto whx;
	uqe: goto jhl;
	xhe: goto ufr;
	obx: putchar('u'); goto gby;
	mvf: putchar('l'); goto shp;
	bes: putchar('e'); goto wsn;
	lid: goto qxs;
	ndh: goto tkd;
	plu: goto del;
	zhm: goto xqh;
	rzi: goto dkt;
	jgm: goto gfz;
	abg: goto bis;
	awq: goto ugw;
	ipl: goto aub;
	qvh: goto gqc;
	myv: putchar(' '); goto sjl;
	qjz: goto abi;
	xqc: goto ecg;
	ies: putchar('I'); goto fyh;
	qoy: putchar('H'); goto uyk;
	ula: goto vdg;
	mku: goto azv;
	eux: goto hcu;
	dvp: putchar('p'); goto vqg;
	zfn: goto phg;
	oai: goto fnt;
	gkx: goto hwi;
	sti: putchar(' '); goto kyx;
	dmo: goto ryb;
	mtr: goto vhc;
	eru: putchar('a'); goto jdz;
	kae: goto pfj;
	uhd: putchar(' '); goto jyt;
	pua: goto usc;
	wmb: goto job;
	dyj: goto whb;
	eui: goto rzi;
	ecd: goto psh;
	uqz: goto lqw;
	gzy: goto fok;
	gqh: goto esb;
	cel: goto tcd;
	kzt: goto nsj;
	qyp: goto iad;
	kfy: goto ewh;
	pyc: putchar('t'); goto xuw;
	lne: goto pvy;
	emn: goto izj;
	hft: goto fwe;
	cth: goto mcr;
	grl: goto aiy;
	eix: goto alg;
	qiw: goto wum;
	mjh: goto zxo;
	aom: goto mxh;
	yjo: goto hke;
	kmo: goto jpy;
	dqz: goto qje;
	jve: goto bmp;
	uds: putchar(';'); goto zuq;
	qic: goto wlf;
	ilh: goto xid;
	iad: goto nij;
	wxz: putchar(' '); goto ljq;
	iox: goto krn;
	ecg: goto wir;
	wpq: goto nvw;
	stf: goto frl;
	zwo: goto vtl;
	krv: goto gju;
	skg: goto tkc;
	aod: putchar('r'); goto dyx;
	wyr: goto cpf;
	acu: goto jvb;
	fnr: goto efy;
	lsa: goto evq;
	dxi: goto glx;
	dbo: goto bxq;
	enk: goto edp;
	ayx: goto yih;
	qdi: goto lid;
	wlj: putchar('h'); goto ajr;
	isd: goto kqb;
	nqk: goto hgf;
	kcr: goto fbe;
	pbz: putchar('d'); goto xbw;
	vtl: goto twi;
	uwq: goto puh;
	gju: goto asu;
	vhc: goto nez;
	brw: goto lgf;
	fbe: putchar('f'); goto iwf;
	alq: goto auw;
	zmx: goto mku;
	egw: goto ecd;
	enu: goto dyu;
	vfi: goto wae;
	fip: goto ltm;
	mrp: goto rtw;
	ydz: goto kxc;
	ort: goto rsj;
	rsj: goto evb;
	yhl: goto qtw;
	ijn: goto gkx;
	euk: putchar('R'); goto vfi;
	rcl: goto kxm;
	yzi: putchar('\n'); return;
	vca: goto iyg;
	cqt: goto hck;
	qob: goto dov;
	iok: goto hpf;
	tvp: goto and;
	and: goto zwg;
	khe: goto zho;
	edp: goto jrm;
	mjt: goto dln;
	ugw: goto erl;
	gwk: goto kyl;
	txd: goto bdi;
	erl: goto sot;
	onq: goto kfg;
	xzl: goto com;
	vft: goto odz;
	fdz: goto grl;
	xqh: putchar(' '); goto krv;
	qxs: goto uws;
	uyk: goto evg;
	ncd: goto ysn;
	zcy: goto ciq;
	ost: goto giy;
	bdn: goto ipl;
	qst: putchar('i'); goto qvh;
	hcu: goto enu;
	bxg: goto dmo;
	qex: putchar('o'); goto vxa;
	pmz: goto ndh;
	dpw: goto pua;
	xay: goto dck;
	wzd: goto xvz;
	bxf: goto hio;
	mvr: goto odq;
	kby: goto teh;
	ped: goto ilv;
	dml: goto vnl;
	vgc: putchar('i'); goto iok;
	svr: putchar('n'); goto erd;
	fdk: putchar(' '); goto kby;
	lzu: putchar('a'); goto bsl;
	hor: goto nld;
	clp: goto pkx;
	ajb: goto glz;
	lbp: goto svr;
	gyd: goto kxw;
	xgr: goto lzi;
	kfg: goto fkx;
	jqd: goto idn;
	cmt: putchar(' '); goto tkn;
	del: goto dsi;
	hef: goto emn;
	vrm: goto ogx;
	znb: goto mrs;
	yqg: goto tjf;
	gtm: goto bdn;
	xes: goto qof;
	rwy: goto cjx;
	rcz: goto btw;
	aqi: goto obz;
	bkc: goto oek;
	tmx: goto grh;
	lbx: goto nes;
	gcx: goto uqm;
	fkc: goto pmb;
	rjd: goto ify;
	cgm: putchar('.'); goto upy;
	gua: goto ine;
	pmx: goto mgl;
	pya: goto yls;
	mbt: goto ort;
	naf: goto xrn;
	nvm: goto tvp;
	atn: goto uwq;
	sdg: goto sxv;
	qym: goto emu;
	krh: goto gnm;
	fcy: putchar('o'); goto lvj;
	wsi: goto gev;
	gev: goto gzy;
	mrg: goto ocr;
	pzr: goto cqt;
	yot: goto uix;
	auw: goto xyf;
	mxe: goto isd;
	jxv: goto gax;
	gwt: goto obn;
	sjz: goto ohn;
	jda: putchar('t'); goto ixr;
	ocb: goto abg;
	wae: goto ims;
	bmp: putchar(' '); goto txw;
	mif: goto btk;
	jdo: goto ney;
	opj: goto olm;
	wps: goto khb;
	xjo: goto xeq;
	krn: putchar('P'); goto ykd;
	pmb: goto dvf;
	brc: goto bgm;
	yih: goto cmt;
	tjf: goto tpu;
	ohn: goto lzt;
	ljo: goto pmx;
	upy: goto ate;
	sbk: goto kfy;
	nru: goto opk;
	gjd: goto pjr;
	mad: goto wsx;
	mki: goto gsp;
	lhq: putchar(' '); goto vae;
	ndf: goto dpw;
	bac: goto ywu;
	ijq: putchar('t'); goto xpm;
	mbx: goto pca;
	wvq: putchar('T'); goto raj;
	grh: goto wpj;
	bxq: goto wxz;
	ova: goto uds;
	olh: goto iyo;
	eln: goto cgm;
	lra: goto mjh;
	zvx: putchar('h'); goto swp;
	mrs: goto neq;
	vuo: goto bgd;
	ogx: goto qbs;
	teh: goto ydz;
	lpw: putchar('a'); goto evx;
	evb: goto kmo;
	ogt: putchar('B'); goto ula;
	jke: goto wst;
	btz: goto rwy;
	amb: goto rbd;
	vae: goto azd;
	hzu: goto opj;
	ine: goto jve;
	fyh: goto naf;
	aup: goto gta;
	ifp: putchar('T'); goto ydg;
	wsx: putchar('U'); goto hvu;
	cqr: putchar('d'); goto mbx;
	yju: goto vha;
	kng: goto aqi;
	drs: goto jzx;
	hpk: goto agv;
	zuq: goto fyw;
	ufr: goto ypb;
	fvt: goto fcy;
	nkb: goto mqt;
	yoq: goto mad;
	cfp: goto lzu;
	cae: goto ukc;
	lvw: putchar('n'); goto vrm;
	mqt: goto cae;
	eim: goto npj;
	izj: goto mjt;
	oem: goto gcx;
	btw: goto phe;
	odc: goto ajw;
	qof: goto fja;
	hwx: goto kfa;
	tcd: goto ldp;
	kfx: goto tfi;
	gsp: putchar('t'); goto gke;
	zbh: goto amb;
	neq: goto olh;
	uhp: goto skg;
	bgd: goto jhp;
	ajr: goto kha;
	dnv: putchar('.'); goto gpo;
	jrm: putchar('o'); goto dxk;
	pld: goto vwt;
	gio: goto hzu;
	bht: goto clp;
	nsj: goto mtr;
	rmz: putchar('y'); goto eix;
	wfl: goto eln;
	urd: goto syt;
	lpb: goto mif;
	gke: goto cel;
	ztc: goto qtn;
	wgn: goto yet;
	sxv: goto sti;
	xyf: goto bes;
	agk: goto euk;
	ysn: goto mfg;
	nzd: goto ong;
	cks: goto awq;
	hio: putchar('e'); goto vgx;
	idb: goto han;
	zkb: goto mop;
	abi: goto mdp;
	ong: goto ocj;
	dln: goto jxv;
	omb: goto ewc;
	mhc: goto bru;
	dbx: goto drs;
	lan: putchar('t'); goto pou;
	mia: goto rtg;
	hpf: goto aom;
	gqc: putchar('g'); goto znb;
	akr: goto dnv;
	jwv: goto pyc;
	vgx: goto shj;
	vnl: goto fbt;
	bxj: goto eml;
	ljq: goto yvx;
	bsl: goto gtm;
	isa: putchar('I'); goto bxg;
	wum: putchar('i'); goto mia;
	bdi: goto lhg;
	odz: goto eux;
	uld: goto avr;
	aiy: goto vny;
	kap: goto vao;
	smw: putchar('f'); goto ndf;
	kbu: goto ajb;
	hnc: goto wvq;
	yxq: goto lsy;
	vyc: goto opm;
	zdw: goto yxq;
	vdb: putchar('o'); goto ijn;
	qrm: goto sdg;
	mgu: goto wsi;
	mxh: goto vhq;
	hrd: putchar('g'); goto zdx;
	kyx: goto xhe;
	fks: putchar('u'); goto wcn;
	ftb: goto uqz;
	ews: goto nvm;
	rpm: goto kng;
	rdk: goto gio;
	wpj: goto ktf;
	ngk: goto wzd;
	vha: goto lvp;
	qbs: goto wgn;
	zfs: goto fzn;
	vij: goto ljo;
	frl: goto vuo;
	wcn: goto pld;
	rwe: goto ifp;
	wsn: goto tzl;
	ciq: goto xjo;
	fzh: goto onq;
	avi: putchar('S'); goto pya;
	kqb: goto rjd;
	evg: goto fzx;
	dsi: goto gfm;
	qky: goto xay;
	oek: goto wpq;
	erd: goto rpm;
	hui: goto ajs;
	hgf: goto fkc;
	odq: goto lne;
	nxf: goto xqc;
	fzn: goto sjz;
	job: goto kap;
	kdz: putchar('r'); goto qyn;
	fzx: putchar('I'); goto hpk;
	tuw: putchar('m'); goto krh;
	mpl: goto qex;
	pkx: goto nru;
	dxk: goto ohb;
	uej: goto itu;
	uqm: goto sak;
	elb: goto sbk;
	ohk: goto elz;
	ewh: goto jgm;
	azd: goto bdc;
	cve: goto uzo;
	wfe: goto omb;
	vby: goto nkb;
	cew: goto mvf;
	krq: goto phb;
	pmw: goto wps;
	ezu: goto rnb;
	xiw: putchar('!'); goto iwj;
	olm: goto ctz;
	mdp: goto fdk;
	yet: goto ocb;
	rbn: goto egw;
	pwh: goto fzh;
	bgm: goto qst;
	xhw: goto khe;
	ayf: goto yhl;
	rbk: putchar(')'); goto uhp;
	hke: goto tuw;
	kom: goto rwe;
	fsm: goto hor;
	kfa: putchar('h'); goto mbt;
	jwb: goto jmy;
	ybr: goto fju;
	alg: goto kwb;
	wun: goto zbh;
	jyx: putchar('a'); goto sjk;
	khb: putchar(' '); goto ost;
	qmj: goto yex;
	nrk: goto wmb;
	ktf: goto duq;
	rtg: goto ijq;
	xuw: goto lpb;
	ims: goto kom;
	vey: goto pzg;
	giy: goto mki;
	rnw: goto jwb;
	gpl: goto lhq;
	syt: goto atn;
	yvx: goto qky;
	tcp: goto ogt;
	pub: goto dml;
	bmu: goto qmf;
	fnt: goto vwo;
	rky: goto jrg;
	ypb: goto jyg;
	qbh: goto fej;
	pol: goto fnr;
	ewc: goto gyd;
	tnb: goto owy;
	nyi: goto mgu;
	lvj: goto foi;
	nfy: goto rwq;
	sjl: goto vgc;
	jzx: putchar('b'); goto egb;
	bru: putchar(' '); goto lbx;
	dov: goto wfl;
	jsr: goto qjz;
	ita: goto pia;
	ykf: goto xlg;
	hvu: goto vft;
	fok: goto oyg;
	kba: goto txd;
	rwq: goto tnb;
	fkx: goto qyp;
	zwg: goto smw;
	jhl: putchar('e'); goto igh;
	gta: goto kfx;
	giz: goto dir;
	mye: goto yjo;
	gnm: goto gqh;
	yli: goto stf;
	jxu: putchar(' '); goto ova;
	pjr: goto jhg;
	jmy: goto xfa;
	lgf: goto xar;
	nij: goto lvw;
	hjx: goto bkc;
	swp: goto fvt;
	efy: goto hrd;
	dyu: goto uej;
	pia: putchar('r'); goto mhc;
	tfi: putchar('c'); goto qno;
	cjx: goto obx;
	mcr: goto jwv;
	whb: goto hui;
	shj: goto sbc;
	sak: goto mrp;
	cpf: goto ayx;
	mlk: goto tai;
	ohb: goto hmg;
	frz: goto nxf;
	ytz: goto hwb;
	fju: goto qdi;
	wri: goto cew;
	rpy: putchar('u'); goto hjx;
	hxw: goto bht;
	wir: putchar('l'); goto wxj;
	hck: goto lpv;
	pfj: goto gjd;
	rbd: goto fip;
	aub: goto dbo;
	iyg: goto rbn;
	srx: goto pgh;
	ouj: putchar('S'); goto pze;
	pvy: goto wyr;
	glz: goto zhm;
	hmg: goto oem;
	arx: goto bmu;
	oel: goto bxj;
	itu: putchar('s'); goto rwx;
	sot: goto ias;
	txw: goto yxn;
	qty: goto yoq;
	ayu: goto jke;
	ocj: goto vij;
	ney: goto pgq;
	hym: putchar('\n'); goto zkb;
	uix: goto zdw;
	tna: goto gpl;
	nvw: goto six;
	qno: goto rcf;
	bis: putchar('g'); goto qic;
	ftr: goto arx;
	lvp: goto opa;
	ptl: goto oai;
	pgh: putchar(' '); goto qbh;
	vny: goto alq;
	dkt: goto cfp;
	xlg: putchar('.'); goto ucv;
	ukc: putchar(' '); goto isr;
	kha: goto lan;
	fux: goto yli;
	xpm: goto gua;
	wxj: goto fdz;
	twi: putchar('y'); goto snl;
	cwo: goto xpu;
	kjg: goto kcr;
	ukr: goto avi;
	avr: goto kzt;
	ltv: putchar('A'); goto rdk;
	mgl: goto axm;
	xqi: goto hdt;
	hsl: goto hnc;
	esb: goto brc;
	jyg: putchar('g'); goto hxw;
	pkr: goto yum;
	qtw: goto lsa;
	fbt: goto ltv;
	opm: putchar('n'); goto fsm;
	ocr: putchar('e'); goto nfy;
	xid: putchar('o'); goto kba;
	gfm: goto bac;
	opk: goto juw;
	pzx: goto jsr;
	gxl: goto bgf;
	owy: goto zcy;
	emu: putchar('u'); goto lyi;
	blx: goto kdp;
	ltm: putchar(' '); goto lra;
	glx: goto xiw;
	jpy: goto ykf;
	com: goto ypf;
	vhq: goto vsy;
	btk: goto irv;
	mkj: goto ezu;
	pou: goto plu;
	uzo: goto pmw;
	yln: goto cqr;
	jla: goto yzi;
	ypf: goto oel;
	rtw: goto dut;
	fja: goto vca;
	dvf: goto vdb;
	ilv: goto ilh;
	tpc: goto lpw;
	bgf: goto zla;
	raj: goto dqr;
	zho: goto ukr;
	shp: goto cve;
	qmf: goto peh;
	yxn: goto btz;
	hwb: goto mhb;
	gfz: goto ath;
	kxm: goto luf;
	hwi: goto cks;
	ixr: goto vey;
	sbc: putchar(' '); goto eui;
	npj: goto mvr;
	pze: goto wun;
	ldp: goto ojb;
	bni: goto brw;
	gby: goto yot;
	ctz: goto acu;
	pgq: goto dyj;
	onl: goto qym;
	ias: goto rpy;
	iyo: goto wlj;
	ihp: goto jda;
	iwj: goto qmj;
	dxy: goto srx;
	agv: goto pkr;
	qrh: goto bik;
	hdt: goto uqe;
	dck: goto gwt;
	nld: goto ves;
	tkc: goto mlk;
	peh: goto uzn;
	irv: goto dxy;
	dir: goto mrg;
	rnb: putchar('a'); goto rnw;
	phb: goto dbx;
	rcf: goto ped;
	opa: goto isa;
	mfg: goto bie;
	iwf: goto onl;
	uiy: putchar('A'); goto cdm;
	lyi: goto nyi;
	tai: goto jla;
	usc: putchar('u'); goto wri;
	lzt: goto ihp;
	egb: goto frz;
	fwe: goto kjg;
	yex: goto nzd;
	wst: goto cth;
	vdg: putchar('e'); goto eim;
	gax: goto jxu;
	mhb: goto nrk;
	eun: goto tcp;
	idn: goto teo;
	ydg: goto pub;
	ywu: goto xgr;
	teo: putchar('\n'); goto qrh;
	oiz: goto eru;
	ryb: goto ayu;
	dut: goto myv;
	fyw: goto rbk;
	bdc: goto jzi;
	pzg: goto enk;
	lsy: goto rcl;
	fej: goto mye;
	lpv: goto sqh;
	mop: goto zfn;
	dqr: goto yqg;
	lzi: goto uhd;
	evq: goto tmx;
	kxc: goto dvp;
	gpo: goto xzl;
	kdp: putchar('e'); goto jdo;
	drx: goto qrm;
	nez: goto hcx;
	kux: goto zmx;
	igh: goto ews;
	cdm: goto agk;
	duq: putchar('e'); goto kbu;
	xpu: putchar('r'); goto wfe;
	wlf: goto drx;
	sjk: goto mxe;
	obn: putchar('b'); goto ybr;
	zqm: goto hsl;
	rwx: goto uld;
	jvb: goto akr;
	oyg: goto vyc;
	jrg: goto qoy;
	oqv: goto ztc;
	vsy: putchar('s'); goto prh;
	ajw: putchar('k'); goto svx;
	tnf: goto elb;
	ykd: goto bni;
	juw: goto vzi;
	nes: goto mal;
	luf: goto lbp;
	jhg: goto tpc;
	uzn: goto gnw;
	vwt: goto pol;
	vzi: goto mpl;
	dyx: goto blx;
	vwo: goto pmz;
	ify: goto pbz;
	phg: goto qty;
	iat: putchar('t'); goto ngk;
	han: goto hwx;
	bie: goto iox;
	vqg: goto aod;
	jdz: goto kdz;
	xrn: goto xhw;
	ate: goto hef;
	whx: goto dxi;
	obz: goto cwo;
	pca: goto ftr;
	tkn: goto tnf;
	zxo: goto ies;
	eml: goto jqd;
	puh: goto odc;
	six: goto ohk;
	xar: goto uiy;
	tpu: goto rky;
	qtn: goto oiz;
	ath: goto xwl;
	alv: putchar('t'); goto zwo;
	kys: goto ncd;
	ajs: goto gxl;
	bik: goto ftb;
	lqw: goto hym;
	kdt: goto jyx;
	vao: putchar('m'); goto mkj;
	jyt: goto ytz;
	snl: goto ybm;
	tzl: goto kux;
	yls: goto vby;
	azv: goto qob;
	phe: goto alv;
	kwb: goto nqk;
	svx: goto ayf;
	evx: goto krq;
	asu: goto ptl;
	tkd: goto rmz;
	xbw: goto kae;
	rsf: goto ita;
	qyn: goto dqz;
	xvz: goto rcz;
	xda: putchar(' '); goto yju;
	kyl: goto pzx;
	ucv: goto xda;
	qje: goto xqi;
	gnw: goto bxf;
	hcx: putchar('i'); goto pwh;
	isr: goto xes;
	ojb: goto zvx;
	psh: putchar('S'); goto kys;
	mal: goto aup;
	elz: goto rsf;
	zla: goto iat;
	xwl: putchar('c'); goto oqv;
	uws: goto qiw;
	foi: goto fux;
	prh: goto gwk;
	xfa: goto urd;
}

int main() {
	gotoMadness();

	return 0;
}
